### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

### ISSUE THREAD

**Issue by oatsu-gh** [oatsu-gh/oto2lab#1]
ini→lab 変換が落ちる。
最後ノートを分割すると右ブランクの値が失われるのが原因。
対症療法：最後のノートをpauにする。
デバッグ：右ブランクを設定させる or pauを追加する
```
Traceback (most recent call last):
File "oto2lab.py", line 205, in <module>
File "oto2lab.py", line 155, in main_cli
File "oto2lab.py", line 75, in ini2lab_solo
File "utaupy¥convert.py", line 73, in otoini2label
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
```

**Comment by oatsu-gh** [comment]
自動で休符を追加することで対策した。
